steps:
  # Build the container image
  - id: "Build Docker Image"
    name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/${PROJECT_ID}/patlytics-react:$COMMIT_SHA", "."]

  # Push the container image to Container Registry
  - id: "Push Docker Image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/patlytics-react:$COMMIT_SHA"]

  # Deploy container image to Cloud Run
  - id: "deploy"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud beta run deploy patlytics-react \
          --platform managed \
          --region asia-east1 \
          --allow-unauthenticated \
          --image gcr.io/${PROJECT_ID}/patlytics-react:$COMMIT_SHA
images:
  - "gcr.io/${PROJECT_ID}/patlytics-react:$COMMIT_SHA"
options:
  logging: CLOUD_LOGGING_ONLY
